// @ts-ignore
const context = require.context(
  "!!raw-loader!./demo_raw",
  true,
  /\.(js|jsx|ts|tsx|css|less|scss|sass|json|html|vue|svg|png|jpg|jpeg|gif)$/,
);

export const demoFiles: Record<string, string> = {};

context.keys().forEach((key: string) => {
  let fileName = key.replace(/^\.\//, "");
  if (
    !/\.(js|jsx|ts|tsx|css|less|scss|sass|json|html|vue|svg|png|jpg|jpeg|gif)$/.test(
      fileName,
    )
  )
    return;

  // Replicate previous logic: source files go to src/
  const configFiles = [
    "package.json",
    "package-lock.json",
    "utoopack.json",
    "postcss.config.js",
    "tailwind.config.js",
  ];

  if (!configFiles.includes(fileName) && !fileName.startsWith("src/")) {
    fileName = `src/${fileName}`;
  }

  // Skip package-lock.json - it should be generated by deps command
  // if (fileName === "package-lock.json") return;
  // Use .default because raw-loader returns an ES module in recent versions
  const module = context(key);
  demoFiles[fileName] = typeof module === 'string' ? module : module.default;
});
